name: CI
on: [push]
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - uses: jdx/mise-action@9e7f7633ff6f6d6048a9418a68d48f288f50eb14 # v4.2.3
    - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
      with:
        node-version-file: '.tool-versions'
        cache: pnpm
    - run: pnpm install --frozen-lockfile
    - run: pnpm test
  pre-commit:
    name: Pre-Commit
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - uses: andrewaylett/pre-commit-action@61755aa7484671834a2bc66828438c26371b8586 # v4.2.0-27
      env:
        SKIP: dedupe,prettier
